INSERT INTO `category` (`id`, `name`) VALUES
(1, 'Accesorios para Vehículos'),
(2, 'Agro'),
(3, 'Alimentos y Bebidas'),
(4, 'Animales y Mascotas'),
(5, 'Antigüedades y Colecciones'),
(6, 'Arte, Librería y Mercería'),
(7, 'Autos, Motos y Otros'),
(8, 'Bebés'),
(9, 'Belleza y Cuidado Personal'),
(10, 'Cámaras y Accesorios'),
(11, 'Celulares y Teléfonos'),
(12, 'Computación'),
(13, 'Consolas y Videojuegos'),
(14, 'Construcción'),
(15, 'Deportes y Fitness'),
(16, 'Electrodomésticos y Aires Ac.'),
(17, 'Electrónica, Audio y Video'),
(18, 'Entradas para Eventos'),
(19, 'Herramientas'),
(20, 'Hogar, Muebles y Jardín'),
(21, 'Industrias y Oficinas'),
(22, 'Inmuebles'),
(23, 'Instrumentos Musicales'),
(24, 'Joyas y Relojes'),
(25, 'Juegos y Juguetes'),
(26, 'Libros, Revistas y Comics'),
(27, 'Música, Películas y Series'),
(28, 'Ropa y Accesorios'),
(29, 'Salud y Equipamiento Médico'),
(30, 'Servicios'),
(31, 'Souvenirs, Cotillón y Fiestas'),
(32, 'Otras categorías');